### PR TITLE
Refactor Angular bits out of common code

### PR DESCRIPTION
**Pull request by roncohen**
- ServiceContainer is now general and does not have anything Angular specific
- TransactionService gained a getCurrentTransaction() for DRYness
- TransactionService is now responsible for scheduleTransactionSend
  instead of ServiceContainer doing it.
- isPlatformSupport renamed to isPlatformSupported
- isAngularSupport renamed to isAngularSupported and moved to its own file. 
  It should probably be a service later

### CODE REVIEW

**Comment by jahtalab** [comment]
* I think TransactionService shouldn't be dependent on OpbeatBackend, the scheduling can happen anywhere
* I think we should not put too much logic in opbeat-angular, since this script is executed as soon as it's loaded, not very testable.
* it seems to me that we need an intermediate service for things like scheduling and isAngularSupported

**Comment by jahtalab** [comment]
* Also with ServiceFactory there's no need for ServiceContainer.

**Comment by roncohen** [comment]
Thanks @jahtalab. 

* What do you mean "scheduling can happen anywhere" ?
* Good idea to move things out of opbeat-angular.js.
* What would the scheduling service do?
* If ServiceFactory is obsolete, i suggest we get rid of that in a separate PR.

**Comment by roncohen** [comment]
What do you think about moving the sequence from opbeat-angular.js into ngOpbeat? That's already doing `isPlatformSupported` and `isAngularSupported`

**Comment by roncohen** [comment]
After a quick discussion offline we agreed that:

* I'll move the initialization logic out of `opbeat-angular.js` and into ngOpbeat
* The call to `scheduleTransactionSend` moves back into `serviceContainer` for now to increase testability.

**Comment by roncohen** [comment]
@jahtalab i moved the logic now. There's a test failing. Could you help me take a look at it? It has to do with boostrapping angular.

**Pull request merged**
